mybatis-plus:
  mapper-locations: classpath*:mappers/*Mapper.xml

spring:
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:config.yaml

server:
  port: 8081
